main_nfa_simulation: 
	g++ -g -c main_nfa_simulation.cc
	g++ -g -c main_functions.cc
	g++ -g -c alphabet.cc
	g++ -g -c nfa.cc
	g++ -g -c state.cc
	g++ -g -c chain.cc
	g++ -o -g p07_nfa_simulation main_nfa_simulation.o main_functions.o alphabet.o nfa.o state.o chain.o 
