# Universidad de La Laguna
# Escuela Superior de Ingeniería y Tecnología
# Grado en Ingeniería Informática
# Informática Básica
#
# @author F. de Sande
# @date 8 Jun 2020
# @brief Makefile file for the video tutorial
# 
# @see https://www.youtube.com/watch?v=rJ-C8q7KOew

all: compile link

compile:
	g++ -c main.cc

link:
	g++ -o main main.o

clean:
	rm -f *.o main *~
